### ISSUE TITLE
Pantheon calendar libsoup error

### ISSUE THREAD

**Issue by rainer2208** [arcolinux/arcob-calamares-config-pantheon#1]
Hi, i couldn't' find a specific page for the pantheon-calendar package, so i just posted the issue here.. hoping someone might be able to assist.  

Over the last couple months, the pantheon calendar has shown some difficulties on Arch, and as of the recent updates i got eager and i thought i give it a go.

The installation went smooth, but when i try to run the calendar it won't open and from the command line with io.elementary.calendar  i receive the following error:

```
(process:2485): libsoup-ERROR **: 15:37:32.790: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Trace/breakpoint trap (core dumped)
```
I have the pantheon-desktop installed and chadwm, but it doesn't make a difference if i run the former or the latter. 

The issue has already an answers [here](https://github.com/elementary/calendar/issues/770) on the elementary github page, with the recommendation to "Make sure that all of your dependencies (and Calendar) are either using libsoup3 or libsoup2 you can't mix them."

I have libsoup and libsoup3 installed ..

Any ideas?

**Comment by arcolinuxz** [comment]
no
we just install what we get from Arch

this is not a priority desktop at all
